// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FlyButton: typeof import('@wefly/vue-ui/es')['FlyButton']
    FlyCard: typeof import('@wefly/vue-ui/es')['FlyCard']
    FlyInput: typeof import('@wefly/vue-ui/es')['FlyInput']
  }
}
